BASE_DIMENSIONS = [150, 220];
BASE_FRONT_CORNER_RADIUS = BASE_DIMENSIONS[0] / 2;
BASE_REAR_CORNER_RADIUS = 30;

LIFT_FAN_DUCT_DIAM = 80;
LIFT_FAN_DUCT_POSITION = [0, (BASE_DIMENSIONS[1] / 2) - LIFT_FAN_DUCT_DIAM + 10];

THRUST_FAN_DUCT_DIAM = 80;
THRUST_FAN_DUCT_MOUNT_POSITION = [0, 0];

RUDDER_MOUNT_POSITION = [0, 0];
